# Generated by Django 4.2.10 on 2024-02-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('serial', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('url', models.CharField(default='#', max_length=100)),
            ],
        ),
    ]
