# Generated by Django 4.2.10 on 2024-02-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmenu',
            name='serial',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='serial',
            field=models.IntegerField(unique=True),
        ),
    ]
