# Generated by Django 4.2.10 on 2024-02-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_daily',
            field=models.IntegerField(default=None),
        ),
    ]
