# Generated by Django 4.2.10 on 2024-02-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_price_alter_property_price_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='monthly_discount_percent',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_daily',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='weekly_discount_percent',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='yearly_discount_percent',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
