# Generated by Django 4.2.10 on 2024-02-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_monthly_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
