# Generated by Django 4.2.10 on 2024-02-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
