# Generated by Django 4.2.10 on 2024-02-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_delete_amenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='property.amenity'),
        ),
    ]
