# Generated by Django 4.2.10 on 2024-02-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_delete_addon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Add-on Services',
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='property.addon'),
        ),
    ]
