# Generated by Django 4.2.10 on 2024-02-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_addon_alter_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='addons',
            field=models.ManyToManyField(to='property.addon'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='property.amenity'),
        ),
    ]
