# Generated by Django 4.2.10 on 2024-02-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_property_addons_alter_property_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.CreateModel(
            name='RentProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.property')),
                ('status', models.CharField(blank=True, choices=[('Ready', 'Ready'), ('Off-Plan', 'Off-Plan')], max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
            ],
            bases=('property.property',),
        ),
    ]
