# Generated by Django 4.2.10 on 2024-02-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_remove_property_price_remove_property_purpose_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentproperty',
            options={'verbose_name_plural': 'Rent Properties'},
        ),
    ]
