# Generated by Django 4.2.10 on 2024-02-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_rentproperty_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentProperty',
        ),
    ]
