# Generated by Django 4.2.10 on 2024-02-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_delete_rentproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.property')),
                ('status', models.CharField(blank=True, choices=[('Ready', 'Ready'), ('Off-Plan', 'Off-Plan')], max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Buy Properties',
            },
            bases=('property.property',),
        ),
        migrations.RemoveField(
            model_name='property',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='property',
            name='monthly_discount_percent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_daily',
        ),
        migrations.RemoveField(
            model_name='property',
            name='weekly_discount_percent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='yearly_discount_percent',
        ),
        migrations.CreateModel(
            name='RentProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.property')),
                ('price_daily', models.IntegerField(blank=True, default=None, null=True)),
                ('weekly_discount_percent', models.IntegerField(blank=True, default=None, null=True)),
                ('monthly_discount_percent', models.IntegerField(blank=True, default=None, null=True)),
                ('yearly_discount_percent', models.IntegerField(blank=True, default=None, null=True)),
                ('addons', models.ManyToManyField(blank=True, to='property.addon')),
            ],
            options={
                'verbose_name_plural': 'Rent Properties',
            },
            bases=('property.property',),
        ),
    ]
