# Generated by Django 4.2.10 on 2024-02-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_buyproperty_remove_property_addons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='guests',
        ),
    ]
