# Generated by Django 4.2.10 on 2024-02-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_rentproperty_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
