# Generated by Django 4.2.10 on 2024-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproperty',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Off-Plan', 'Off-Plan')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
