# Generated by Django 4.2.10 on 2024-02-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_rentproperty_price_daily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentproperty',
            name='guests',
        ),
    ]
