# Generated by Django 4.2.10 on 2024-02-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_remove_rentproperty_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproperty',
            name='total_guests',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
