# Generated by Django 4.2.10 on 2024-02-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_rentproperty_total_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproperty',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
