# Generated by Django 4.2.10 on 2024-02-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_alter_buyproperty_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area_sqft',
            field=models.IntegerField(),
        ),
    ]
