# Generated by Django 4.2.10 on 2024-02-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_alter_propertyimage_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='bathrooms',
            new_name='baths',
        ),
    ]
