# Generated by Django 4.2.10 on 2024-02-22 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_rename_bathrooms_property_baths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.bath'),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.bed'),
        ),
    ]
