# Generated by Django 4.2.10 on 2024-02-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_bath_bed_alter_property_baths_alter_property_beds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='property',
            name='beds',
        ),
    ]
