# Generated by Django 4.2.10 on 2024-02-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_remove_property_baths_remove_property_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
