# Generated by Django 4.2.10 on 2024-02-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_alter_property_baths_alter_property_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bath',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
