# Generated by Django 4.2.10 on 2024-02-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0031_alter_bath_number_alter_bed_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_property_bookings', to='property.rentproperty'),
        ),
    ]
